LandingPage/urls.py
from django.urls import path 
from .views import LandingPageView #SignUpView, CustomLoginView
from . import views

app_name = 'LandingPage'

urlpatterns = [
    path('', LandingPageView.as_view(), name='LandingPage'), 
    path('signup/', views.register, name='signup'),
    path('login/', views.login_view, name='loginmain'),
    path('logout/', views.logout_view, name='logout'),
    # path('signup/', SignUpView.as_view(), name='signup'),
    # path('login/', CustomLoginView.as_view(), name='login'),

]

LandingPage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    USER_TYPE_CHOICES = [
        ('supplier', 'Supplier'),
        ('farmer', 'Farmer'),
    ]
    email = models.EmailField('Email address', unique=True)
    user_type = models.CharField('User Type', max_length=20, choices=USER_TYPE_CHOICES, blank=True, null=True)

LandingPage/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User


class LoginForm(forms.Form):
    # SUPPLIER_CHOICES = [
    #     ('fertilizer', 'Fertilizer Supplier'),
    #     ('equipementandmachineries', 'Equipment And Machineries Supplier'),
    #     ('seed', 'Seed Supplier'),
    #     ('coldstorage', 'Cold Storage Supplier'),
    #     ('cattleandfisheries', 'Cattle And Fisheries Supplier'),
    # ]

    username = forms.CharField(
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    # supplier_type = forms.ChoiceField(
    #     choices=SUPPLIER_CHOICES,
    #     widget=forms.Select(attrs={"class": "form-control"})
    # )

class SignUpForm(UserCreationForm):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]


    SUPPLIER_CHOICES = [
        ('fertilizer', 'Fertilizer Supplier'),
        ('equipementandmachineries', 'Equipment And Machineries Supplier'),
        ('seed', 'Seed Supplier'),
        ('coldstorage', 'Cold Storage Supplier'),
        ('cattleandfisheries', 'Cattle And Fisheries Supplier'),
    ]

    USER_TYPE_CHOICES = [
        ('supplier', 'Supplier'),
        ('farmer', 'Farmer'),
    ]

    email = forms.EmailField(
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    fname = forms.CharField(
        max_length=10,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    lname = forms.CharField(
        max_length=10,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    gender = forms.ChoiceField(
        choices=GENDER_CHOICES,
        widget=forms.Select(attrs={"class": "form-control"})
    )
    house = forms.CharField(
        max_length=12,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    street = forms.CharField(
        max_length=12,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    thana = forms.CharField(
        max_length=12,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    zip = forms.CharField(
        max_length=10,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    city = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    contactnumber = forms.CharField(
        max_length=15,
        widget=forms.TextInput(attrs={"class": "form-control"})
    )
    supplierType = forms.ChoiceField(
        choices=SUPPLIER_CHOICES,
        widget=forms.Select(attrs={"class": "form-control"})
    )
    userType = forms.CharField(
        max_length=20,
        #choices = USER_TYPE_CHOICES,
        #widget=forms.Select(attrs={"class": "form-control"}),
        widget=forms.HiddenInput(),
        initial="Supplier"
    )


    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'user_type')

LandingPage/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import SignUpForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from Supplier.models import sTable
from Farmer.models import fTable
from testserver.views import dataPassingOverSeas
from Farmer.views import dataPassingOverSeasFarmer

# Create your views here.
class LandingPageView(TemplateView):
    template_name = 'LandingPage/LandingPage.html'

# class TestView(TemplateView):
#     template_name = 'testserver/base.html'

def register(request):
    msg = None 
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            # form.save()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            fname = form.cleaned_data['fname']
            lname = form.cleaned_data['lname']
            gender = form.cleaned_data['gender']
            house = form.cleaned_data['house']
            street = form.cleaned_data['street']
            thana = form.cleaned_data['thana']
            zip_code = form.cleaned_data['zip']
            city = form.cleaned_data['city']
            contact_number = form.cleaned_data['contactnumber']
            supplier_type = form.cleaned_data['supplierType']
            user_type = form.cleaned_data['user_type']

            if user_type == "Supplier":
                sTable.objects.create(
                    email=email,
                    fname=fname,
                    lname=lname,
                    gender=gender,
                    house=house,
                    street=street,
                    thana=thana,
                    zip=zip_code,
                    city=city,
                    contactnumber=contact_number,
                    supplierType=supplier_type,
                )
            else:
                fTable.objects.create(
                    email=email,
                    fname=fname,
                    lname=lname,
                    gender=gender,
                    house=house,
                    street=street,
                    thana=thana,
                    zip=zip_code,
                    city=city,
                    contactnumber=contact_number,
                )

            user = get_user_model().objects.create_user(
                username  = username,
                password = password,
                email = email ,
                first_name = fname,
                last_name = lname,
                user_type = user_type,
            )

            msg = 'user created'
            #return redirect('login_view')
            return render(request, 'LandingPage/LandingPage.html')
        else:
            msg = 'form is not Valid'
    else:
        form = SignUpForm()
    return render(request, 'LandingPage/register.html', {"form" : form, "msg" : msg})



# @login_required
def login_view(request):
    form = LoginForm(request.POST or None)
    msg = None 
    if request.method == "POST":
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            # print(user)
            if user is not None:
                login(request, user)
                # print(request.user.user_type)
                if request.user.user_type == "Supplier":
                    # print(user.get_username())
                    dataPassingOverSeas(user.get_username())
                    return redirect('testserver/')
                elif request.user.user_type == "farmer":
                    dataPassingOverSeasFarmer(user.get_username())
                    return redirect('Farmer/')
                elif request.user.user_type == "ARDOFFICER":
                    return redirect('ARDOfficer/')
                else:
                    msg = "User doesn't exits!"
                # return redirect('testserver/')
            else:
                msg = "invalid credentials"
        else:
            msg = "Error validating form"
    return render(request, 'LandingPage/loginmain.html', {'form':form, 'msg':msg})






def logout_view(request):
    logout(request)
    return redirect(reverse('LandingPage/LandingPage.html'))

LandingPage/templates/LandingPage/LandingPage.html
{% extends 'landing.html' %}


{% block contentHome %}
<a class="navbar-brand text-white" href="#">Logo</a>
{% endblock %}

LandingPage/templates/LandingPage/loginmain.html
{% load static %}  
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'LandingPage/logincss/signin.css' %}">
    <title>Document</title>
</head>
<body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'LandingPage:LandingPage' %}">BinaryFarming</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'LandingPage:LandingPage' %}">Home</a>
              </li>
              <!-- <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li> -->
              <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li> -->
              <!-- <li class="nav-item">
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
              </li> -->
            </ul>
            <form class="d-flex ">
              <a href="{% url 'LandingPage:loginmain' %}" class="btn btn-outline-success me-2" type="button">Sign In</a>
              <a href="{% url 'LandingPage:signup' %}" class="btn btn-outline-success" type="button">Sign Up</a>
              
            </form>
          </div>
        </div>
      </nav> 

    <!-- Sign In -->
    <section class="vh-100" style="background-color: #eee;">
        <div class="container h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-lg-12 col-xl-11">
              <div class="card text-black" style="border-radius: 25px;">
                <div class="card-body p-md-5">
                  <div class="row justify-content-center">
                    <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
      
                      <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign In</p>
      
                      <form method="POST" class="mx-1 mx-md-4">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit"  value="Login" class="button-30" role="button">
                        <!-- 
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-envelope fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example3c">Your Email</label>
                            <input type="email" placeholder="Enter your email" id="form3Example3c" class="form-control" />
                          </div>
                        </div>
                        
                        
                        <div class="d-flex flex-row align-items-center mb-4">
                          <i class="fas fa-lock fa-lg me-3 fa-fw"></i>
                          <div class="form-outline flex-fill mb-0">
                            <label class="form-label" for="form3Example4c">Password</label>
                            <input type="password" placeholder="Enter the password" id="form3Example4c" class="form-control" />
                          </div>
                        </div>

                        <div style="position: relative;right: -17px;width: 96%;" class="user-dropdown">
                          <label class="form-label" for="form3Example4c">User</label>
                          <select class="form-select" aria-label="Default select example">
                            <option selected>Select User</option>
                            <option value="1">One</option>
                            <option value="2">Two</option>
                            <option value="3">Three</option>
                          </select>
                        </div>

                        
      
                        <div class="form-check d-flex justify-content-center mb-2 mt-4">
                          <p class="">
                            Don't have an account? <a href="./signup.html">Sign up</a>
                          </p>
                        </div>
      
                        <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                          <button type="button" class="btn btn-primary btn-lg">Sign In</button>
                        </div> Email -->

                      {% if msg is None %}
                        <div style="color: red;">
                          <p> May Allah Bless you!</p>
                        </div>
                      {% else %}
                        <div style="color: red;">
                          {{ msg }}
                        </div>
                      {% endif %}
      
                      </form>
                      
                    </div>
                    <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
      
                      <img src="{% static 'HomePage/logincss/signIn-Image.jpg' %}"
                        class="img-fluid" alt="Sample image">
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
</body>
</html>

LandingPage/templates/LandingPage/register.html
{% load static %}  
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
  <link rel="stylesheet" href="{% static 'LandingPage/css/signup.css' %}">
  <title>Document</title>
</head>

<body>
  <!-- Page style start -->
  <style>
    .gradient-custom {
    background: #f093fb;
    
    background: -webkit-linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1));
    
    background: linear-gradient(to bottom right, rgba(240, 147, 251, 1), rgba(245, 87, 108, 1))
    }
    
    .card-registration .select-input.form-control[readonly]:not([disabled]) {
    font-size: 1rem;
    line-height: 2.15;
    padding-left: .75em;
    padding-right: .75em;
    }
    .card-registration .select-arrow {
    top: 13px;
    };
  </style>
  <!-- Page style end -->

  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'LandingPage:LandingPage' %}">BinaryFarming</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'LandingPage:LandingPage' %}">Home</a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li> -->
          <!-- <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li> -->
          <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li> -->
        </ul>
        <form class="d-flex ">
          <a href="{% url 'LandingPage:loginmain' %}" class="btn btn-outline-success me-2" type="button">Sign In</a>
          <a href="{% url 'LandingPage:signup' %}" class="btn btn-outline-success" type="button">Sign Up</a>
          
        </form>
      </div>
    </div>
  </nav> 

  <!-- Sign Up -->

  <section class=" gradient-custom">
    <div class="container py-5 h-100">
      <div class="row justify-content-center align-items-center h-100">
        <div class="col-12 col-lg-9 col-xl-7">
          <div class="card shadow-2-strong card-registration" style="border-radius: 15px;">
            <div class="card-body p-4 p-md-5">
              <h3 class="mb-4 pb-2 pb-md-0 mb-md-5">Registration Form</h3>

            <form  method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                
                <input type="submit"  value="Register" class="button-30" role="button">
              <!-- <div class="row">
                <div class="col-md-6 mb-4">
                   
                  <div class="form-outline">
                    <label class="form-label" for="firstName">First Name</label>
                
                  </div>

                </div>
                <div class="col-md-6 mb-4">
                  
                  <div class="form-outline">
                    <label class="form-label" for="lastName">Last Name</label>
                    <input type="text" id="lastName" class="form-control form-control-lg" />
                  </div>

                </div>
              </div>

             
              <div class="row">
                
                <div class="col-md-6 mb-4 d-flex align-items-center">
                  <div class="form-outline datepicker w-100">
                    <label for="house" class="form-label">House</label>
                    <input type="text" class="form-control form-control-lg" id="house" />
                  </div>

                </div>

                <div class="col-md-6 mb-4 d-flex align-items-center">

                  <div class="form-outline datepicker w-100">
                    <label for="street" class="form-label">Street</label>
                    <input type="text" class="form-control form-control-lg" id="street" />
                  </div>

                </div>

              
                <div class="col-md-6 mb-4 d-flex align-items-center">

                  <div class="form-outline datepicker w-100">
                    <label for="thana" class="form-label">Thana</label>
                    <input type="text" class="form-control form-control-lg" id="thana" />
                  </div>

                </div>

               
                <div class="col-md-6 mb-4 d-flex align-items-center">

                  <div class="form-outline datepicker w-100">
                    <label for="zip" class="form-label">Zip</label>
                    <input type="text" class="form-control form-control-lg" id="zip" />
                  </div>

                </div>

               
                <div class="col-md-6 mb-4 d-flex align-items-center">

                  <div class="form-outline datepicker w-100">
                    <label for="city" class="form-label">City</label>
                    <input type="text" class="form-control form-control-lg" id="city" />
                  </div>

                </div>

                <div class="col-md-6 mb-4">

                  <h6 class="mb-2 pb-1">Gender: </h6>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="femaleGender"
                      value="option1" checked />
                    <label class="form-check-label" for="femaleGender">Female</label>
                  </div>

                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="inlineRadioOptions" id="maleGender"
                      value="option2" />
                    <label class="form-check-label" for="maleGender">Male</label>
                  </div>

                </div>
              </div>


              <div class="row">
             
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <label class="form-label" for="emailAddress">Email</label>
                    <input type="email" id="emailAddress" class="form-control form-control-lg" />
                  </div>

                </div>

              
                <div class="col-md-6 mb-4 pb-2">

                  <div class="form-outline">
                    <label class="form-label" for="phoneNumber">Phone Number</label>
                    <input type="tel" id="phoneNumber" class="form-control form-control-lg" />
                  </div>

                </div>

                <div class="form-outline">
                  <label class="form-label" for="password">Password</label>
                  <input type="password" id="password" class="form-control form-control-lg" />
                </div>

              </div>
              </div>

              <div class="row">

                
                <div style="display: flex; flex-direction: column; padding: 0 8%;" class="col-md-6 mb-4 pb-2">

                  <label class="form-label select-label">Choose Livestock</label>
                  <select class="select form-control-lg">
                    <option value="1" disabled>Choose Livestock</option>
                    <option value="2">Subject 1</option>
                    <option value="3">Subject 2</option>
                    <option value="4">Subject 3</option>
                  </select>

                </div>

                 Crop Type 
                <div style="display: flex; flex-direction: column; padding: 0 8%;" class="col-md-6 pb-2">

                  <label class="form-label select-label">Choose Crop Type</label>
                  <select class="select form-control-lg">
                    <option value="1" disabled>Choose Crop Type</option>
                    <option value="2">Subject 1</option>
                    <option value="3">Subject 2</option>
                    <option value="4">Subject 3</option>
                  </select>

                </div>

              </div>

              Submit Button
              <div class="pt-2 text-center mb-4">
                <input class="btn btn-primary btn-lg" type="submit" value="Submit" />
              </div> -->

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

</body>

</html>