testserver/urls.py
from django.urls import path 
from .views import TestView, ThankuView, TestForm, TestCreateView, TestProductCreateView, TestProductListView, test_view, ProfileView, ProductDetailView, ProductUpdateView, ProductDeleteView, OrderListView
from . import views

app_name = 'testserver'

urlpatterns = [
    path('', test_view, name='test'),
    path('thanku/', ThankuView.as_view(), name='thanku'),
    path('profile/', ProfileView, name='profile'),
    path('testform/', TestForm.as_view(), name='testform'),
    path('testform2/', TestCreateView.as_view(), name='testform2'),
    path('product/', TestProductCreateView.as_view(), name='product'),
    path('productlist/', TestProductListView.as_view(), name='productlist'),
    path('orderlist/', OrderListView.as_view(), name='orderlist'),
    path('productupdateview/<int:pk>/', ProductUpdateView.as_view(), name='productupdate'),
    path('productdeleteview/<int:pk>/', ProductDeleteView.as_view(), name='productdelete'),
]

testserver/models.py
from django.db import models
from django import forms


# Create your models here.

# Widgets 


class CustomForm(forms.Form):
    custom_field = forms.CharField()



class Test(models.Model):
    fname = models.CharField(max_length=30)

    def __str__ (self):
        return f"{self.fname}"


class bug(models.Model):
    id = models.IntegerField(primary_key=True, default=784)
    user = models.CharField(max_length=30, default='Hasib')


class bug2(models.Model):
    id = models.IntegerField(primary_key=True, default=784)
    user = models.CharField(max_length=30, default='Farmer')

testserver/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from testserver.forms import Testform
from Supplier.models import sTable
from django.shortcuts import get_object_or_404
from LandingPage.models import User
from .models import bug
from Product.models import pTable
from testserver.models import Test
from django.urls import reverse_lazy
from Order.models import oTable
from Product.models import pTable


# Create your views here.

def bugg(loggedinperson):
    bug_instance, created = bug.objects.get_or_create(id=784)
    if not created:
        bug_instance.user = loggedinperson
        bug_instance.save() 
    else:
        bug.objects.create()


bugg("HasibNormal")


def get_supplier_by_username(email):
    supplier = get_object_or_404(User, email=email)
    bugg(supplier.pk)

def get_user_by_username(username):
    supplier = get_object_or_404(User, username=username)
    get_supplier_by_username(supplier.email)


def dataPassingOverSeas(username):
    get_user_by_username(username)
    # bugg(username)





#supplierInstance = get_user_by_username(userInstance.email)


class TestView(TemplateView):
    template_name = 'testserver/base.html'


def ProfileView(request):
    template_name = 'testserver/profile.html'

    bug_instance, created = bug.objects.get_or_create(id=784) 
    # print(sTable.objects.get_or_create(supplierID = bug_instance.user))
    
    if  bug_instance.user == 'HasibNormal':
        pass 
    else:
        s_table_instance, s_table_created = sTable.objects.get_or_create(supplierID=bug_instance.user)
        orders = oTable.objects.filter(supplierID=s_table_instance.supplierID)
        orderList = [order.orderId for order in orders]
        prodId = [order.productID for order in orders] 
        prodIdL = prodId[-1]
        #print(prodIdL.productID)
        prodInsance = pTable.objects.filter(productID=prodIdL.productID)
        productname = [order.productName for order in prodInsance] 
        prodName = productname[-1]
        LastOrder = orderList[-1]

    context = {
        's_table_instance': s_table_instance,
        'prodname' : prodName,
        'LastOrder' : LastOrder,
    }

    return render(request, template_name, context)


def test_view(request):
    template_name = 'testserver/base.html'

    bug_instance, created = bug.objects.get_or_create(id=784) 
    # print(sTable.objects.get_or_create(supplierID = bug_instance.user))
    
    if  bug_instance.user == 'HasibNormal':
        pass 
    else:
        totalSale = 0
        s_table_instance, s_table_created = sTable.objects.get_or_create(supplierID=bug_instance.user)
        # order_instance, created = oTable.objects.get_or_create(supplierID=s_table_instance.supplierID)
        orders = oTable.objects.filter(supplierID=s_table_instance.supplierID)
        orderList = [order.totalPrice for order in orders]
        prodId = [order.productID for order in orders] 
        prodIdL = prodId[-1]
        #print(prodIdL.productID)
        prodInsance = pTable.objects.filter(productID=prodIdL.productID)
        productname = [order.productName for order in prodInsance] 
        prodName = productname[-1]
        LastOrder = orderList[-1]
        for price in orderList:
            totalSale += price
            print(price)
        Income_Tax = float(totalSale)*(0.10)

    context = {
        's_table_instance': s_table_instance,
        'totalSale' : totalSale,
        'LastOrder' : LastOrder,
        'prodname' : prodName,
        'Income' : Income_Tax,
    }

    return render(request, template_name, context)


class ThankuView(TemplateView):
    template_name = 'testserver/thanku.html'

class TestForm(FormView):
    form_class = Testform
    template_name = 'TestView'

    success_url = reverse_lazy('thanku')

    def form_valid(self, form):
        
        print(form.cleaned_data)
        return super().form_valid(form)
    

class TestCreateView(CreateView):
    model = Test 
    fields = "__all__"
    success_url = "/thanku/"


class TestProductCreateView(CreateView):
    model = pTable
    fields = ['productName', 'productPrice']
    success_url = reverse_lazy('testserver:productlist')

    def form_valid(self, form):
        bug_instance, created = bug.objects.get_or_create(id=784) 
        
        if  bug_instance.user == 'HasibNormal':
            pass 
        else:
            s_table_instance, s_table_created = sTable.objects.get_or_create(supplierID=bug_instance.user)
        # Assign the supplier instance to the TestProduct before saving
        form.instance.supplierID  = s_table_instance

        # p_table_instance = form.save()
        # s_table_instance = sTable.objects.get(supplierID=form.instance.supplierID)

        return super().form_valid(form)



class TestProductListView(ListView):
    model = pTable
    # queryset = pTable.objects.order_by('productName')
    
    
    def get_queryset(self):
        bug_instance, created = bug.objects.get_or_create(id=784) 
        
        if  bug_instance.user == 'HasibNormal':
            pass 
        else:
            s_table_instance, s_table_created = sTable.objects.get_or_create(supplierID=bug_instance.user)

        queryset = pTable.objects.filter(supplierID =  s_table_instance.supplierID )

        return queryset


class ProductDetailView(DetailView):
    model = pTable

class ProductUpdateView(UpdateView):
    model = pTable
    fields = ['productName', 'productPrice']
    success_url = reverse_lazy('testserver:productlist')


    # context_object_name = "ProductList" // For changing object List


class ProductDeleteView(DeleteView):
    Model = pTable
    success_url = reverse_lazy('testserver:productlist')


    def get_queryset(self):
        bug_instance, created = bug.objects.get_or_create(id=784) 
        
        if  bug_instance.user == 'HasibNormal':
            pass 
        else:
            s_table_instance, s_table_created = sTable.objects.get_or_create(supplierID=bug_instance.user)

        queryset = pTable.objects.filter(supplierID =  s_table_instance.supplierID )

        return queryset



class OrderListView(ListView):
    model = oTable
    # queryset = pTable.objects.order_by('productName')
    
    
    def get_queryset(self):
        bug_instance, created = bug.objects.get_or_create(id=784) 
        
        if  bug_instance.user == 'HasibNormal':
            pass 
        else:
            s_table_instance, s_table_created = sTable.objects.get_or_create(supplierID=bug_instance.user)

        queryset = oTable.objects.filter(supplierID =  s_table_instance.supplierID )

        return queryset

testserver/templates/Order/oTable_list.html
{% extends 'SupplierDashboardBase.html' %}


{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
<li><a href="{% url 'testserver:productlist' %}">
  <i class="fas fa-wallet"></i>
  <span class="nav-item">Products</span>
</a></li>  
{% endblock %}


{% block contentDashHead %}
  <h1>Orders</h1>
{% endblock %}


{% block contentButton %}
<!-- <a href="{% url 'testserver:product' %}" class="button-30" role="button">Add New Products</a> -->
{% endblock %}


{% block contentDash %}

<div class="table-box">
  <div class="table-row table-head">
      <div class="table-cell first-cell">
          <p>Order ID</p>
      </div>
      <div class="table-cell">
          <p>Order Date</p>
      </div>
      <div class="table-cell ">
          <p>Quantity</p>
      </div> 
      <div class="table-cell last-cell">
          <p>ProductID</p>
      </div> 
  </div>



  {% for products in object_list %}
  <div class="table-row">
    <div class="table-cell first-cell">
        <p>{{ products.orderId }}</p>
    </div>
    <div class="table-cell">
        <p>{{ products.orderDate }}</p>
    </div>
    <div class="table-cell ">
        <p>{{ products.quantity }}</p>
    </div> 
    <div class="table-cell last-cell">
        <p>{{ products.productID_id }}</p>
    </div> 
</div>
{% endfor %}  



    
    

</div> 

{% endblock %}

testserver/templates/Product/pTable_confirm_delete.html
{% extends 'SupplierDashboardBase.html' %}
{% load static %}  

{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
  <li><a href="{% url 'testserver:productlist' %}">
    <i class="fas fa-wallet"></i>
    <span class="nav-item">Products</span>
  </a></li>  
{% endblock %}


{% block contentButton %}
  <!-- <p>Supplier ID: {{ s_table_instance.supplierID }}</p> -->
  <!-- <h2> Welcome Back {{ s_table_instance.fname }} {{ s_table_instance.lname }} </h2> -->
{% endblock %}

{% block contentDashHead %}
  <h1>DELETE</h1>
{% endblock %}


{% block contentDash %}
<div style="
    margin-left: 40%;">
    <img src="{% static 'testserver/delete.jpg' %}" alt="">
</div>
<div>
    <h2 style="margin-left: 30%;  margin-top: 2%;">Do you want to Delete {{ ptable.productName }} with a ProductID {{ ptable.productID }} ?</h2>
</div>
<div style="
margin-left: 50%; margin-top: 1%;">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Submit" class="button-30" role="button">
      </form>
</div>

{% endblock %}

testserver/templates/Product/pTable_detail.html
{{ ptable }}
{{  products  }}

testserver/templates/Product/pTable_form.html
{% extends 'SupplierDashboardBase.html' %}
{% load static %} 

{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
<li><a href="{% url 'testserver:productlist' %}">
  <i class="fas fa-wallet"></i>
  <span class="nav-item">Products</span>
</a></li>  
{% endblock %}


{% block contentDashHead %}
  <h1>Products</h1>
{% endblock %}


{% block contentButton %}
<a href="{% url 'testserver:productlist' %}" class="button-30" role="button">Go to Product List</a>
{% endblock %}

{% block contentDash %}
    <!-- <div style="
    padding: 18%;
    margin-left: 20%;">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="button-30" role="button" style="
            margin-top: 2%;
            margin-left: 15%;">
          </form>
    </div> -->

    <div style="
    margin-left: 22%;">
      <img src="{% static 'testserver/prod.png' %}" alt="">
    </div>
    <form class="row g-3" method="post" action="" style="
    padding: 1%;">
      {% csrf_token %}
      
      <div class="col-auto">
        {{ form.productName.label_tag }}
        {{ form.productName }}
      </div>
    
      <div class="col-auto" style="margin-left: 35%;">
        {{ form.productPrice.label_tag }}
        {{ form.productPrice }}
      </div>
    
      <div class="col-auto">
        <input type="submit" value="Submit" class="button-30" role="button" style="
        margin-top: 1%;
        margin-left: 45%;">
      </div>
    </form>

    
{% endblock %}

testserver/templates/Product/pTable_list.html
{% extends 'SupplierDashboardBase.html' %}


{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
<li><a href="{% url 'testserver:productlist' %}">
  <i class="fas fa-wallet"></i>
  <span class="nav-item">Products</span>
</a></li>  
{% endblock %}


{% block contentDashHead %}
  <h1>Products</h1>
{% endblock %}


{% block contentButton %}
<a href="{% url 'testserver:product' %}" class="button-30" role="button">Add New Products</a>
{% endblock %}


{% block contentDash %}

<div class="table-box">
  <div class="table-row table-head">
      <div class="table-cell first-cell">
          <p>Product Name</p>
      </div>
      <div class="table-cell">
          <p>Product Price</p>
      </div>
      <div class="table-cell ">
          <p>Update Details</p>
      </div> 
      <div class="table-cell last-cell">
          <p>Delete Product</p>
      </div> 
  </div>



  {% for products in object_list %}
  <div class="table-row">
    <div class="table-cell first-cell">
        <p>{{ products.productName }}</p>
    </div>
    <div class="table-cell">
        <p>{{ products.productPrice }}</p>
    </div>
    <div class="table-cell ">
        <p>Update Details</p>
    </div> 
    <div class="table-cell last-cell">
        <p>Delete Product</p>
    </div> 
</div>
{% endfor %}  



    
    

</div> 

{% endblock %}

testserver/templates/testserver/base.html
{% extends 'SupplierDashboardBase.html' %}


{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
  <li><a href="{% url 'testserver:productlist' %}">
    <i class="fas fa-wallet"></i>
    <span class="nav-item">Products</span>
  </a></li>  
{% endblock %}


{% block contentButton %}
  <!-- <p>Supplier ID: {{ s_table_instance.supplierID }}</p> -->
  <!-- <h2> Welcome Back {{ s_table_instance.fname }} {{ s_table_instance.lname }} </h2> -->
{% endblock %}

{% block contentDashHead %}
  <h1>HOME</h1>
{% endblock %}


{% block contentDash %}
<div class="main-body">
  <h2>Supplier Dashboard</h2>
  <div class="promo_card">
    <h1>Welcome Supplier {{ s_table_instance.fname }} {{ s_table_instance.lname }}</h1>
    <span>
      <p>We are delighted to welcome you to our Supplier Dashboard, the gateway to seamless collaboration and efficient management.
         Your presence here marks a significant step toward strengthening our partnership and ensuring a smoother flow of information and resources.
      </p>
      <p>
        In this secure space, you will find powerful tools and insights tailored to enhance your experience and streamline your interactions with our platform.
         We understand the pivotal role suppliers play in our success, and this dashboard is designed with your needs in mind.
      </p>
      <p>
        Thank you for being an essential part of our network. Let's embark on this journey together, navigating toward mutual growth and success.
        Feel free to explore the features, and don't hesitate to reach out if you have any questions or feedback.
      </p>
    </span>
    <button>Learn More</button>
  </div>
  
  <!-- Card -->
  <div class="ag-format-container">
    <div class="ag-courses_box">
      
      
      <div class="ag-courses_item">
        <a href="#" class="ag-courses-item_link">
          <div class="ag-courses-item_bg"></div>
          
          <div class="ag-courses-item_title">
            Total Lifetime Sale
          </div>
          
          <div class="ag-courses-item_date-box">
            BDT: 
            <span class="ag-courses-item_date">
              {{ totalSale }}
            </span>
          </div>
        </a>
      </div>
      
      <div class="ag-courses_item">
        <a href="#" class="ag-courses-item_link">
          <div class="ag-courses-item_bg"></div>
          
          <div class="ag-courses-item_title">
            Last Sale
          </div>
  
          <div class="ag-courses-item_date-box">
            {{ prodname }} </br>
            BDT: 
            <span class="ag-courses-item_date">
              {{ LastOrder  }} 
            </span>
          </div>
        </a>
      </div>    
                      
      <div class="ag-courses_item">
        <a href="#" class="ag-courses-item_link">
          <div class="ag-courses-item_bg"></div>
          
          <div class="ag-courses-item_title">
            Lifetime Income Tax
          </div>
          
          <div class="ag-courses-item_date-box">
            BDT: 
            <span class="ag-courses-item_date">
              {{ Income }}
            </span>
          </div>
        </a>
      </div>                    
  
    </div>
  </div>


{% endblock %}

testserver/templates/testserver/profile.html
{% extends 'SupplierDashboardBase.html' %}

{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
  <li><a href="{% url 'testserver:productlist' %}">
    <i class="fas fa-wallet"></i>
    <span class="nav-item">Products</span>
  </a></li>  
{% endblock %}

{% block contentDashHead %}
  <h1>PROFILE</h1>
{% endblock %}

{% block Profile %}
<div class="course-box">
          
  <div class="wrapper">
  <div class="right">
    <div class="info">
        <h3>Information</h3>
        <div class="info_data">
             <div class="data">
                <h4>Full Name</h4>
                <p>{{ s_table_instance.fname }} {{ s_table_instance.lname }}</p>
             </div>
             <div class="data">
               <h4>Email</h4>
                <p>{{ s_table_instance.email }}</p>
          </div>
        </div>
        <div class="info_data">
             <div class="data">
                <h4>Gender</h4>
                <p>Male</p>
             </div>
             <div class="data">
              <h4>Supplier Type</h4>
                <p>{{ s_table_instance.supplierType }}</p>
          </div>
        </div>
        <div class="info_data">
             <div class="data">
                <h4>Contact Number</h4>
                <p>{{ s_table_instance.contactnumber }}</p>
             </div>
             <div class="data">
              <h4>Address</h4>
              <p>{{ s_table_instance.house }}, {{ s_table_instance.street }}, {{ s_table_instance.thana }}, {{ s_table_instance.zip }} {{ s_table_instance.city }}</p>
          </div>
        </div>
    </div>
  
  <div class="projects">
        <h3>Recent Orders</h3>
        <div class="projects_data">
             <div class="data">
                <h4>Product Name</h4>
                <p>{{ prodname }}</p>
             </div>
             <div class="data">
               <h4>Order ID</h4>
                <p>{{ LastOrder }}</p>
          </div>
        </div>
    </div>
  </div>           
</div>

</div>
<!-- </section>

</section> -->

</div>
{% endblock %}

{% block contentButton %}
  <!-- <p>Supplier ID: {{ s_table_instance.supplierID }}</p> -->
  <!-- <h2> Welcome Back {{ s_table_instance.fname }} {{ s_table_instance.lname }} </h2> -->
{% endblock %}


{% block contentDash %}
{{ s_table_instance.fname }} {{ s_table_instance.lname }} 

{% endblock %}

testserver/templates/testserver/testproduct_form.html
{% extends 'SupplierDashboardBase.html' %}


{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
<li><a href="{% url 'testserver:productlist' %}">
  <i class="fas fa-wallet"></i>
  <span class="nav-item">Products</span>
</a></li>  
{% endblock %}


{% block contentDashHead %}
  <h1>Products</h1>
{% endblock %}


{% block contentButton %}
<a href="{% url 'testserver:productlist' %}" class="button-30" role="button">Go to Product List</a>
{% endblock %}

{% block contentDash %}
    <!-- <div style="
    padding: 18%;
    margin-left: 20%;">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit" class="button-30" role="button" style="
            margin-top: 2%;
            margin-left: 15%;">
          </form>
    </div> -->


    <form class="row g-3" method="post" action="" style="
    padding: 18%;">
      {% csrf_token %}
      
      <div class="col-auto">
        {{ form.productName.label_tag }}
        {{ form.productName }}
      </div>
    
      <div class="col-auto">
        {{ form.productPrice.label_tag }}
        {{ form.productPrice }}
      </div>
    
      <div class="col-auto">
        <input type="submit" value="Submit" class="button-30" role="button" style="
        margin-top: 2%;
        margin-left: 45%;">
      </div>
    </form>

    
{% endblock %}

testserver/templates/testserver/testproduct_list.html
{% extends 'SupplierDashboardBase.html' %}


{% block contentHome %}
<li><a href="{% url 'testserver:test' %}">
  <i class="fas fa-home"></i>
  <span class="nav-item">Home</span>
</a></li>
{% endblock %}


{% block contentProduct %}
<li><a href="{% url 'testserver:productlist' %}">
  <i class="fas fa-wallet"></i>
  <span class="nav-item">Products</span>
</a></li>  
{% endblock %}


{% block contentDashHead %}
  <h1>Products</h1>
{% endblock %}


{% block contentButton %}
<a href="{% url 'testserver:product' %}" class="button-30" role="button">Add New Products</a>
{% endblock %}


{% block contentDash %}

<div class="table-box">
  <div class="table-row table-head">
      <div class="table-cell first-cell">
          <p>Product Name</p>
      </div>
      <div class="table-cell">
          <p>Product Price</p>
      </div>
      <div class="table-cell ">
          <p>Update Details</p>
      </div> 
      <div class="table-cell last-cell">
          <p>Delete Product</p>
      </div> 
  </div>



  {% for products in object_list %}
  <div class="table-row">
    <div class="table-cell first-cell">
        <p>{{ products.productName }}</p>
    </div>
    <div class="table-cell">
        <p>{{ products.productPrice }}</p>
    </div>
    <div class="table-cell ">
        <p>Update Details</p>
    </div> 
    <div class="table-cell last-cell">
        <p>Delete Product</p>
    </div> 
</div>
{% endfor %}  



    
    

</div> 

{% endblock %}