BinaryFarming/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('LandingPage.urls')),
    path('login/testserver/', include('testserver.urls')),
    path('login/Farmer/', include('Farmer.urls')),
    path('login/ARDOfficer/', include('ARDOfficer.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Farmer/urls.py
from django.urls import path
from . import views

app_name = 'Farmer'



urlpatterns = [
   path('',views.page_view,name="dashboard"),
   path('order/', views.order,name="order"),
   path('priceOffer/', views.priceOffer,name="priceOffer"),
   path('consultancy/', views.consultancy,name="consultancy"),
   path('base/', views.base),
   path('form/', views.form),
]
 

FrontEnd Templates/Hasib/BinaryFarming/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testserver.urls')),
]

LandingPage/urls.py
from django.urls import path 
from .views import LandingPageView #SignUpView, CustomLoginView
from . import views

app_name = 'LandingPage'

urlpatterns = [
    path('', LandingPageView.as_view(), name='LandingPage'), 
    path('signup/', views.register, name='signup'),
    path('login/', views.login_view, name='loginmain'),
    path('logout/', views.logout_view, name='logout'),
    # path('signup/', SignUpView.as_view(), name='signup'),
    # path('login/', CustomLoginView.as_view(), name='login'),

]

testserver/urls.py
from django.urls import path 
from .views import TestView, ThankuView, TestForm, TestCreateView, TestProductCreateView, TestProductListView, test_view, ProfileView, ProductDetailView, ProductUpdateView, ProductDeleteView, OrderListView
from . import views

app_name = 'testserver'

urlpatterns = [
    path('', test_view, name='test'),
    path('thanku/', ThankuView.as_view(), name='thanku'),
    path('profile/', ProfileView, name='profile'),
    path('testform/', TestForm.as_view(), name='testform'),
    path('testform2/', TestCreateView.as_view(), name='testform2'),
    path('product/', TestProductCreateView.as_view(), name='product'),
    path('productlist/', TestProductListView.as_view(), name='productlist'),
    path('orderlist/', OrderListView.as_view(), name='orderlist'),
    path('productupdateview/<int:pk>/', ProductUpdateView.as_view(), name='productupdate'),
    path('productdeleteview/<int:pk>/', ProductDeleteView.as_view(), name='productdelete'),
]

templates/SupplierDashboardBase.html
<!-- <span style="font-family: verdana, geneva, sans-serif;"> -->
    {% load static %}  
    <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <title>Supplier Dashboard</title>
        <link rel="stylesheet" href="style.css" />
        <!-- Font Awesome Cdn Link -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"/>
        <link rel="stylesheet" href="{% static 'testserver/base.css' %}">
        
      </head>
      <body>
        <div class="container">
          <nav>
            <ul>
              <li><a href="#" class="logo">
                <img src="./image/signIn-Image.avif" alt="">
                <span class="nav-item">Supplier</span>
              </a></li>
              {% block contentHome %}
  
              {% endblock %}
              <li><a href="{% url 'testserver:profile' %}">
                <i class="fas fa-user"></i>
                <span class="nav-item">Profile</span>
              </a></li>
              {% block contentProduct %}
  
              {% endblock %}
              <li><a href="{% url 'testserver:orderlist' %}">
                <i class="fas fa-solid fa-truck"></i>
                <span class="nav-item">Order</span>
              </a></li>
              <li><a href="">
                <i class="fas fa-tasks"></i>
                <span class="nav-item">Shipment</span>
              </a></li>
              <!-- <li><a href="">
                <i class="fas fa-cog"></i>
                <span class="nav-item"></span>
              </a></li> -->
              <li><a href="">
                <i class="fas fa-question-circle"></i>
                <span class="nav-item">Analytics</span>
              </a></li>
              <li><a href="{% url 'LandingPage:LandingPage' %}" class="logout">
                <i class="fas fa-sign-out-alt"></i>
                <span class="nav-item">Log out</span>
              </a></li>
            </ul>
          </nav>
      
          <section class="main">
            <div class="main-top">
                {% block contentDashHead %}
  
                {% endblock %}
              <i class="fas fa-user-cog"></i>
            </div>


            <!-- Profile  -->
            {% block Profile %}

            {% endblock %}
            <!-- <div class="main-skills">
              <div class="card">
                <i class="fas fa-laptop-code"></i>
                <h3>Web developemt</h3>
                <p>Join Over 1 million Students.</p>
                <button>Get Started</button>
              </div>
              <div class="card">
                <i class="fab fa-wordpress"></i>
                <h3>WordPress</h3>
                <p>Join Over 3 million Students.</p>
                <button>Get Started</button>
              </div>
              <div class="card">
                <i class="fas fa-palette"></i>
                <h3>graphic design</h3>
                <p>Join Over 2 million Students.</p>
                <button>Get Started</button>
              </div>
              <div class="card">
                <i class="fab fa-app-store-ios"></i>
                <h3>IOS dev</h3>
                <p>Join Over 1 million Students.</p>
                <button>Get Started</button>
              </div>
            </div> -->
      
            <section class="main-course">
                {% block contentButton %}
  
                {% endblock %}

                <br>
                <br>

                {% block contentDash %}
  
                {% endblock %}
              <!-- <div class="course-box">
                <ul>
                  <li class="active">In progress</li>
                  <li>explore</li>
                  <li>incoming</li>
                  <li>finished</li>
                </ul>
                <div class="course">
                  <div class="box">
                    <h3>HTML</h3>
                    <p>80% - progress</p>
                    <button>continue</button>
                    <i class="fab fa-html5 html"></i>
                  </div>
                  <div class="box">
                    <h3>CSS</h3>
                    <p>50% - progress</p>
                    <button>continue</button>
                    <i class="fab fa-css3-alt css"></i>
                  </div>
                  <div class="box">
                    <h3>JavaScript</h3>
                    <p>30% - progress</p>
                    <button>continue</button>
                    <i class="fab fa-js-square js"></i>
                  </div>
                </div>
              </div> -->
            </section>
          </section>
        </div>
      </body>
      </html></span>